eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
           defaultZone: http://localhost:8761/eureka/
   instance:
      hostname: localhost
microservice:
    payment-service:
       endpoints:
          endpoint:
              uri: http://PAYMENT-MICROSERVICES
    order-service:
       endpoints:
          endpoint:
              uri: http://PAYMENT-MICROSERVICES
